# /etc/netplan/50-cloud-init.yaml
network:
    ethernets:
        eth0:
            addresses:
              - 10.0.0.101/24
            gateway4: 10.0.0.1
            nameservers:
              addresses: [10.0.0.101]
            optional: true
    version: 2